Repository gomate-community/rageval, pull requests merged in 2024-03, with the labels that each got.

#67 Hotfix/validate data refactor
  rageval/metrics/base.py
Labels: enhancement

#73 update readme
  README.md
Labels: documentation

#54 add rouge metric
  rageval/metrics/__init__.py
  rageval/metrics/_answer_rouge_correctness.py
  requirements.txt
  tests/units/test_answer_rouge.py
Labels: enhancement

#69 add disambig f1 score
  rageval/metrics/__init__.py
  rageval/metrics/_answer_disambig_f1.py
  requirements.txt
  tests/units/test_answer_disambig_f1.py
Labels: enhancement

#68 add citation metric
  rageval/metrics/__init__.py
  rageval/metrics/_answer_citation_precision.py
  rageval/metrics/_answer_citation_recall.py
  rageval/utils/__init__.py
  rageval/utils/check_utils.py
  tests/units/test_answer_citation_precision.py
  tests/units/test_answer_citation_recall.py
Labels: enhancement

#80 fix a bug of bleu
  rageval/metrics/_answer_bleu.py
  tests/units/__pycache__/test_answer_bleu.cpython-310-pytest-8.0.1.pyc.2320
Labels: bug

#81 supplement docs
  README.md
  rageval/metrics/_answer_disambig_f1.py
  rageval/metrics/_answer_rouge_correctness.py
  rageval/metrics/_context_reject_rate.py
  tests/units/test_context_reject_rate.py
Labels: documentation

#79 add auto benchmark
  benchmarks/__init__.py
  benchmarks/auto/README.md
  benchmarks/auto/auto_benchmark.py
  benchmarks/auto/corpus/corpus.json
  benchmarks/auto/corpus/few_shot_cases.json
  benchmarks/auto/output/dataset.json
  benchmarks/auto/prompt.py
  benchmarks/auto/run.sh
  benchmarks/utils.py
  rageval/models/openai.py
Labels: enhancement

#87 add asqa benchmark
  benchmarks/ASQA/README.md
  benchmarks/ASQA/asqa_benchmark.py
  benchmarks/ASQA/generate.py
  benchmarks/ASQA/output/dataset.jsonl
  benchmarks/ASQA/output/result_dataset.jsonl
  benchmarks/ASQA/output/results.jsonl
  benchmarks/ASQA/prompts.py
  benchmarks/ASQA/run.sh
  benchmarks/__init__.py
  benchmarks/auto/README.md
  benchmarks/base.py
  benchmarks/utils.py
  rageval/metrics/_answer_exact_match.py
  rageval/metrics/_answer_rouge_correctness.py
  rageval/models/openai.py
  tests/units/test_answer_disambig_f1.py
  tests/units/test_answer_exect_match.py
Labels: enhancement

#90 move instructGPT to OpenAILLM
  benchmarks/ASQA/generate.py
  rageval/models/openai.py
  tests/units/test_openai_api.py
Labels: enhancement
